[package]
name = "certificate"
version = "0.1.0"
entrypoint = "main.typ"
description = "Certificate template with decorative design and recipient name input."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "certificate"
default = "certificate.json"
