[package]
name = "multi_input"
version = "0.1.0"
entrypoint = "main.typ"
description = "Template with multiple JSON inputs."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "one"
default = "data.json"
schema = "data.schema.json"

[[tool.oicana.inputs]]
type = "json"
key = "two"
default = "data.json"
schema = "data.schema.json"

[[tool.oicana.inputs]]
type = "json"
key = "three"
default = "data.json"
schema = "data.schema.json"
