[package]
name = "multi_input"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Niklas Eicker <git@nikl.me>"]
description = "An example template with multiple json inputs."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "one"
default = "data.json"
schema = "data.schema.json"

[[tool.oicana.inputs]]
type = "json"
key = "two"
default = "data.json"
schema = "data.schema.json"

[[tool.oicana.inputs]]
type = "json"
key = "three"
default = "data.json"
schema = "data.schema.json"
