[package]
name = "fonts"
version = "0.1.0"
entrypoint = "main.typ"
description = "Template showcasing custom font integration and multilingual text rendering."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "sample.json"
schema = "schema.json"
