[package]
name = "dependency"
version = "0.1.0"
entrypoint = "main.typ"
authors = ["Niklas Eicker <git@nikl.me>"]
description = "An example Oicana template with a third party dependency."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "sample.json"
schema = "schema.json"
