[package]
name = "dependency"
version = "0.1.0"
entrypoint = "main.typ"
description = "Template using the third-party package CeTZ for a chart."

[tool.oicana]
manifest_version = 1

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "sample.json"
schema = "schema.json"
