[package]
name = "table"
version = "0.1.0"
entrypoint = "template.typ"
description = "Example Oicana template with a table filled by a json input."

[tool.oicana]
manifest_version = 1
tests = "tests"

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "data.json"
schema = "data.schema.json"
