[package]
name = "table"
version = "0.1.0"
entrypoint = "main.typ"
description = "Dynamic table populated from JSON data."

[tool.oicana]
manifest_version = 1
tests = "tests"

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "data.json"
schema = "data.schema.json"
