[package]
name = "table"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Niklas Eicker <git@nikl.me>"]
description = "An example template with a table."

[tool.oicana]
manifest_version = 1
tests = "tests"

[[tool.oicana.inputs]]
type = "json"
key = "data"
default = "data.json"
schema = "data.schema.json"
