name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate-links:
    name: Check for dead links in docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check readme links
        run: npx linkinator README.md

  check-format:
    name: check typst files format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: typstyle, oicana_cli@0.1.0-alpha.5
      - name: check format
        run: typstyle templates --diff -v
      - name: run tempalte tests
        run: oicana test -a
